Feat/move allow and deny checks to crypto
protokol/guardian pull request #71
Opened 2021-02-18 17:39 UTC by amacar

## Summary

### What changes are being made?
Move allow/deny checks from handlers to crypto
Closes CU-8yrych

### Why are these changes necessary?
To check asset validity before even reaching node endpoint

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-02-18 17:39 UTC, kristjank commented
Task linked: [CU-8yrych feat(guardian): move allow and deny checks from handler to crypto](https://app.clickup.com/t/8yrych)

2021-02-18 19:14 UTC, KovacZan requested changes
Would be nice if we add functional tests for this and confirm that this really works in real scenario.
Replace `build()` method with `getStruct()` to bypass validation schema on client side, that way server side should reject transaction.

2021-02-19 10:33 UTC, amacar commented
> Would be nice if we add functional tests for this and confirm that this really works in real scenario.
> Replace `build()` method with `getStruct()` to bypass validation schema on client side, that way server side should reject transaction.

Added functional tests for duplicates.

2021-02-19 12:24 UTC, KovacZan approved these changes

2021-02-19 12:59 UTC, merged